### PR TITLE
Release v8.0.2: dependency updates + Rust 1.91+ build fix

### LINKED ISSUE #38: Build fails on rust 1.91
# Summary

This crate builds in 1.90 but no more in 1.91 (also not in 1.93.0-nightly). There seems to be some kind of regression with lifetime checking.

(It would be nice if someone would verify this, so it's not a my_computer thing)

# The error

```commandline
error[E0310]: the parameter type `S` may not live long enough
   --> src/lib.rs:664:5
    |
664 | /     {
665 | |         let search_stream = self
666 | |             .ldap
667 | |             .streaming_search(base, scope, filter.filter().as_str(), attributes)
...   |
676 | |         to_native_stream(search_stream)
677 | |     }
    | |     ^
    | |     |
    | |_____the parameter type `S` must be valid for the static lifetime...
    |       ...so that the type `S` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
663 |         S: AsRef<str> + Send + Sync + 'a + 'static,
    |                                          +++++++++

error[E0310]: the parameter type `A` may not live long enough
   --> src/lib.rs:664:5
    |
664 | /     {
665 | |         let search_stream = self
666 | |             .ldap
667 | |             .streaming_search(base, scope, filter.filter().as_str(), attributes)
...   |
676 | |         to_native_stream(search_stream)
677 | |     }
    | |     ^
    | |     |
    | |_____the parameter type `A` must be valid for the static lifetime...
    |       ...so that the type `A` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
662 |         A: AsRef<[S]> + Send + Sync + 'a + 'static,
    |                                          +++++++++
```

# Possible culprits

- https://github.com/rust-lang/rust/issues/148854
- https://github.com/rust-lang/rust/issues/147285
  - This was already in 1.90 though

# Workaround

Use rust 1.90 for now.

Perhaps something could be done to the code as well but surely the suggested fix of adding a `'static` bound is wrong?

### PR DESCRIPTION
**Pull request by keaz**
## Summary
- bump crate version to `8.0.2`
- update direct dependencies in `Cargo.toml` to current compatible versions
- fix Rust 1.91+ lifetime build regression in streaming search by returning boxed streams (without adding `'static` bounds)

## Validation
- `cargo test` (unit, integration with Docker OpenDJ, pool tests, and doctests)

Closes #38

___

## **CodeAnt-AI Description**
**Release v8.0.2: dependency updates and Rust 1.91+ build fix**

### What Changed
- Builds now succeed on Rust 1.91+ by returning boxed, pinned streams for streaming search APIs, avoiding previous lifetime errors with pooled clients.
- Updated multiple dependencies and crate version to 8.0.2 so the library uses newer patch releases for transitive crates.
- Streaming search behavior for pooled clients no longer requires artificial external lifetimes, making pooled usage compile cleanly.

### Impact
`✅ Builds on Rust 1.91+`
`✅ Easier use with connection pools (no lifetime compile errors)`
`✅ Uses newer dependency releases`
<details>
<summary><strong>💡 Usage Guide</strong></summary>

### Checking Your Pull Request
Every time you make a pull request, our system automatically looks through it. We check for security issues, mistakes in how you're setting up your infrastructure, and common code problems. We do this to make sure your changes are solid and won't cause any trouble later.

### Talking to CodeAnt AI
Got a question or need a hand with something in your pull request? You can easily get in touch with CodeAnt AI right here. Just type the following in a comment on your pull request, and replace "Your question here" with whatever you want to ask:
<pre>
<code>@codeant-ai ask: Your question here</code>
</pre>
This lets you have a chat with CodeAnt AI about your pull request, making it easier to understand and improve your code.

#### Example
<pre>
<code>@codeant-ai ask: Can you suggest a safer alternative to storing this secret?</code>
</pre>

### Preserve Org Learnings with CodeAnt
You can record team preferences so CodeAnt AI applies them in future reviews. Reply directly to the specific CodeAnt AI suggestion (in the same thread) and replace "Your feedback here" with your input:
<pre>
<code>@codeant-ai: Your feedback here</code>
</pre>
This helps CodeAnt AI learn and adapt to your team's coding style and standards.

#### Example
<pre>
<code>@codeant-ai: Do not flag unused imports.</code>
</pre>

### Retrigger review
Ask CodeAnt AI to review the PR again, by typing:
<pre>
<code>@codeant-ai: review</code>
</pre>

### Check Your Repository Health
To analyze the health of your code repository, visit our dashboard at [https://app.codeant.ai](https://app.codeant.ai). This tool helps you identify potential issues and areas for improvement in your codebase, ensuring your repository maintains high standards of code health.

</details>

### CODE REVIEW

File: src/lib.rs
Comment (Iizuki) [inline src/lib.rs:1]: The build was already fixed in #40. These code changes are just reintroducing the previous attempt at fixing it. They should be removed.

**Review by Iizuki — CHANGES_REQUESTED** [review]

**Comment by Iizuki** [comment]
I bumped the deps in #53 so this is now obsolete.
