### PR TITLE
The stream returning is valid only for lifetime 'a, which matches the…

### LINKED ISSUE #38: Build fails on rust 1.91
# Summary

This crate builds in 1.90 but no more in 1.91 (also not in 1.93.0-nightly). There seems to be some kind of regression with lifetime checking.

(It would be nice if someone would verify this, so it's not a my_computer thing)

# The error

```commandline
error[E0310]: the parameter type `S` may not live long enough
   --> src/lib.rs:664:5
    |
664 | /     {
665 | |         let search_stream = self
666 | |             .ldap
667 | |             .streaming_search(base, scope, filter.filter().as_str(), attributes)
...   |
676 | |         to_native_stream(search_stream)
677 | |     }
    | |     ^
    | |     |
    | |_____the parameter type `S` must be valid for the static lifetime...
    |       ...so that the type `S` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
663 |         S: AsRef<str> + Send + Sync + 'a + 'static,
    |                                          +++++++++

error[E0310]: the parameter type `A` may not live long enough
   --> src/lib.rs:664:5
    |
664 | /     {
665 | |         let search_stream = self
666 | |             .ldap
667 | |             .streaming_search(base, scope, filter.filter().as_str(), attributes)
...   |
676 | |         to_native_stream(search_stream)
677 | |     }
    | |     ^
    | |     |
    | |_____the parameter type `A` must be valid for the static lifetime...
    |       ...so that the type `A` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
662 |         A: AsRef<[S]> + Send + Sync + 'a + 'static,
    |                                          +++++++++
```

# Possible culprits

- https://github.com/rust-lang/rust/issues/148854
- https://github.com/rust-lang/rust/issues/147285
  - This was already in 1.90 though

# Workaround

Use rust 1.90 for now.

Perhaps something could be done to the code as well but surely the suggested fix of adding a `'static` bound is wrong?

### PR DESCRIPTION
**Pull request by Jonke**
The stream returning is valid only for lifetime 'a, which matches the lifetime of the borrowed client and SearchStram<'a,S,A>

the compiler inferred that the returned impl Stream<...> needed to be 'static, but your generic parameters S and A were only constrained to live at least as long as 'a (the lifetime tied to &'a mut self), not necessarily for 'static.

this PR;   “the stream I’m returning is valid only for lifetime 'a,” which matches the lifetime of the borrowed client and SearchStream<'a, S, A> you’re wrapping.

You do not need to force S and A to be 'static; they can still carry non-'static data as long as they live at least 'a.

### CODE REVIEW

**Review by keaz — APPROVED** [review]
LGTM

**Comment by Iizuki** [comment]
@Jonke 

Ohh this is interesting. I was under the impression that the lifetime captured in the `use` already expressed the intended lifetime. Apparently not then..?

**Comment by Jonke** [comment]
I blatantly  copy and paste some old explanation, that was once given to me, for rustc --explain E0310

"if the parameter type T contains references, variables of this type **may** not live long enough
...so that type T will meet its required lifetime bounds
help: consider excluding types with non-static references by adding an explicit lifetime bound..."

**Comment by Iizuki** [comment]
Hmmh it still strikes me like capturing the lifetime should have been enough (as it used to be).

**Comment by Jonke** [comment]
Ah, now I think I get what you are referring too, the use of use<> as a precise capture of impl at return position.
But I don't think I have ever seen that used like this, ie inside a concrete Result type ?, I have only seen that pattern at the starting of the return, ie impl SomeTraite + OtherTrait+ use<'a,T>. 
Like:
-> impl Iterator<Item = usize> + use<>
Not that I'm saying that it wouldn't work as in this code,
-> Result<impl Stream<Item = Result<Record, Error>> + use<'a, F, A, S>, Error>
 just that I haven't seen it used like that.
