### ISSUE TITLE
Build fails on rust 1.91

### ISSUE THREAD

**Issue by Iizuki** [keaz/simple-ldap#38]
# Summary

This crate builds in 1.90 but no more in 1.91 (also not in 1.93.0-nightly). There seems to be some kind of regression with lifetime checking.

(It would be nice if someone would verify this, so it's not a my_computer thing)

# The error

```commandline
error[E0310]: the parameter type `S` may not live long enough
   --> src/lib.rs:664:5
    |
664 | /     {
665 | |         let search_stream = self
666 | |             .ldap
667 | |             .streaming_search(base, scope, filter.filter().as_str(), attributes)
...   |
676 | |         to_native_stream(search_stream)
677 | |     }
    | |     ^
    | |     |
    | |_____the parameter type `S` must be valid for the static lifetime...
    |       ...so that the type `S` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
663 |         S: AsRef<str> + Send + Sync + 'a + 'static,
    |                                          +++++++++

error[E0310]: the parameter type `A` may not live long enough
   --> src/lib.rs:664:5
    |
664 | /     {
665 | |         let search_stream = self
666 | |             .ldap
667 | |             .streaming_search(base, scope, filter.filter().as_str(), attributes)
...   |
676 | |         to_native_stream(search_stream)
677 | |     }
    | |     ^
    | |     |
    | |_____the parameter type `A` must be valid for the static lifetime...
    |       ...so that the type `A` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
662 |         A: AsRef<[S]> + Send + Sync + 'a + 'static,
    |                                          +++++++++
```

# Possible culprits

- https://github.com/rust-lang/rust/issues/148854
- https://github.com/rust-lang/rust/issues/147285
  - This was already in 1.90 though

# Workaround

Use rust 1.90 for now.

Perhaps something could be done to the code as well but surely the suggested fix of adding a `'static` bound is wrong?

**Comment by Jonke** [comment]
See my PR https://github.com/keaz/simple-ldap/pull/40 for a fix for this issue

**Comment by Iizuki** [comment]
Rust 1.92.0 seems to have fixed the regression. The original code compiles again, but it's not like the adopted fix does any harm either so we can just leave it there.
